Issue Resolution: Implement Events Section & Quality Changes
GDG-OnCampus-BU/landing-page-WIP pull request #14
Opened 2024-10-13 10:47 UTC by Saransh-Jainbu

### Issue Number closed Events Section #5 : 
## Important Checklist:
- [✔️ ] You have prettyfied your code (`npx prettier --write .`)
- [✔️] Linted the code using ESLint (`npx eslint . --ext .js,.jsx,.ts,.tsx`)
- [✔️ ] This code is best you could write in terms of quality (we don't mind even if its bad :P)
- [✔️ ] You have attached the screenshot of visible chnages in GUI, if any
- [✔️ ] You have no merge conflicts, you have pulled and rebased your PR branch
- [✔️ ] All CI tests have passed

2024-10-14 13:15 UTC, g4ze commented on src/app/page.js
> +import EventsSection from "@/components/EventsSection"; // Import EventsSection, which includes EventCard and Events
weird comm

2024-10-15 14:04 UTC, g4ze requested changes

2024-10-15 14:04 UTC, g4ze commented on src/app/globals.css
> +/* Add this in your CSS file */
still unresolved

2024-10-15 14:06 UTC, g4ze commented
> [✔️ ] You have attached the screenshot of visible chnages in GUI, if any
unattended

2024-10-15 14:15 UTC, Saransh-Jainbu commented
please refer the issue comment for image changes

2024-10-15 14:17 UTC, g4ze commented
Kindly attach an image here as well pls

2024-10-18 04:12 UTC, g4ze approved these changes

2024-10-18 04:13 UTC, merged